"""Shared 2D world simulator for the localization project.

A differential-drive robot wanders a 20x20 m field with point landmarks.
It receives noisy odometry commands and range-bearing observations of
landmarks within sensor range (data association is given: observations
carry landmark ids).

Students do NOT edit this file — it is the harness both they and the
grader run against.
"""

from __future__ import annotations

import numpy as np

WORLD_SIZE = 20.0
LANDMARK_RANGE = 8.0
RANGE_SIGMA = 0.4       # sensor noise (m)
BEARING_SIGMA = 0.1     # sensor noise (rad)
ODOM_V_SIGMA = 0.15     # actuation noise on commanded v (m/s)
ODOM_W_SIGMA = 0.10     # actuation noise on commanded omega (rad/s)
DT = 0.25


def wrap(a):
    return -(np.mod(-np.asarray(a) + np.pi, 2 * np.pi) - np.pi)


def arc_step(pose, v, w, dt=DT):
    """Exact twist integration; pose and result are (..., 3) arrays."""
    pose = np.asarray(pose, dtype=float)
    x, y, th = pose[..., 0], pose[..., 1], pose[..., 2]
    w = np.asarray(w, dtype=float)
    v = np.asarray(v, dtype=float)
    straight = np.abs(w) < 1e-9
    w_safe = np.where(straight, 1.0, w)
    r = v / w_safe
    nx = np.where(straight, x + v * np.cos(th) * dt,
                  x + r * (np.sin(th + w * dt) - np.sin(th)))
    ny = np.where(straight, y + v * np.sin(th) * dt,
                  y - r * (np.cos(th + w * dt) - np.cos(th)))
    nth = wrap(th + w * dt)
    return np.stack([nx, ny, nth], axis=-1)


def make_world(seed, n_landmarks=14):
    rng = np.random.default_rng(seed)
    landmarks = rng.uniform(1.0, WORLD_SIZE - 1.0, size=(n_landmarks, 2))
    start = np.array([WORLD_SIZE / 2, WORLD_SIZE / 2, rng.uniform(-np.pi, np.pi)])
    return landmarks, start


def _next_command(pose, w_prev, rng):
    """Wander command: random-walk the turn rate, but steer back toward the
    center when near a wall — keeps the robot in-world WITHOUT clipping
    (clipping would be unmodeled dynamics no filter could track)."""
    v = float(np.clip(rng.normal(0.8, 0.1), 0.4, 1.2))
    margin = 3.5
    near_wall = (
        pose[0] < margin or pose[0] > WORLD_SIZE - margin
        or pose[1] < margin or pose[1] > WORLD_SIZE - margin
    )
    if near_wall:
        desired = np.arctan2(WORLD_SIZE / 2 - pose[1], WORLD_SIZE / 2 - pose[0])
        w = float(np.clip(1.5 * wrap(desired - pose[2]), -0.8, 0.8))
    else:
        w = float(np.clip(w_prev + rng.normal(0, 0.15), -0.6, 0.6))
    return v, w


def observe(pose, landmarks, rng):
    """Noisy (id, range, bearing) for landmarks within sensor range."""
    d = landmarks - pose[:2]
    ranges = np.hypot(d[:, 0], d[:, 1])
    obs = []
    for i in np.flatnonzero(ranges < LANDMARK_RANGE):
        r = ranges[i] + rng.normal(0, RANGE_SIGMA)
        b = wrap(np.arctan2(d[i, 1], d[i, 0]) - pose[2] + rng.normal(0, BEARING_SIGMA))
        obs.append((int(i), float(r), float(b)))
    return obs


def simulate(seed, steps=80, kidnap_at=None):
    """Returns (landmarks, true_traj (steps,3), commands (v,w), observations list)."""
    landmarks, start = make_world(seed)
    rng = np.random.default_rng(seed + 2)
    pose, traj, all_obs = start.copy(), [], []
    v_cmd, w_cmd = np.zeros(steps), np.zeros(steps)
    w_prev = 0.0
    for k in range(steps):
        if kidnap_at is not None and k == kidnap_at:
            pose = np.array([*rng.uniform(4.0, WORLD_SIZE - 4.0, 2),
                             rng.uniform(-np.pi, np.pi)])
        v_cmd[k], w_cmd[k] = _next_command(pose, w_prev, rng)
        w_prev = w_cmd[k]
        v_true = v_cmd[k] + rng.normal(0, ODOM_V_SIGMA)
        w_true = w_cmd[k] + rng.normal(0, ODOM_W_SIGMA)
        pose = arc_step(pose, v_true, w_true)
        traj.append(pose.copy())
        all_obs.append(observe(pose, landmarks, rng))
    return landmarks, np.array(traj), (v_cmd, w_cmd), all_obs


def run_filter(student, seed, steps=80, n_particles=1500, kidnap_at=None,
               global_init=False, inject_frac=0.0):
    """Run the student's particle filter against a simulated world.

    Returns per-step position error (steps,) of the weighted-mean estimate.
    """
    landmarks, traj, (v_cmd, w_cmd), all_obs = simulate(seed, steps, kidnap_at)
    rng = np.random.default_rng(seed + 99)
    _, start = make_world(seed)
    if global_init:
        particles = np.column_stack([
            rng.uniform(0, WORLD_SIZE, n_particles),
            rng.uniform(0, WORLD_SIZE, n_particles),
            rng.uniform(-np.pi, np.pi, n_particles),
        ])
    else:
        particles = start + rng.normal(0, 0.3, size=(n_particles, 3))
        particles[:, 2] = wrap(particles[:, 2])
    weights = np.full(n_particles, 1.0 / n_particles)

    errors = []
    for k in range(steps):
        particles = student.motion_update(particles, v_cmd[k], w_cmd[k], DT, rng)
        if inject_frac > 0:
            particles = student.inject_random(particles, inject_frac, rng)
        if all_obs[k]:
            lik = student.measurement_likelihood(particles, all_obs[k], landmarks)
            weights = weights * np.asarray(lik)
            s = weights.sum()
            weights = np.full(n_particles, 1.0 / n_particles) if s < 1e-300 else weights / s
        if 1.0 / np.sum(weights**2) < n_particles / 2:
            idx = student.systematic_resample(weights, rng)
            particles = particles[idx]
            weights = np.full(n_particles, 1.0 / n_particles)
        est_xy = weights @ particles[:, :2]
        errors.append(float(np.hypot(*(est_xy - traj[k, :2]))))
    return np.array(errors)
